version: "2.3"

services:
  api:
      image: python
      container_name: api
      
      logging:
            driver: "json-file"
            options:
                  max-size: "1m"
                  max-file: "5"

      healthcheck:
            test: curl -f http://api/test
            interval: 60s
            timeout: 10s
            retries: 5
            start_period: 60s

      ports:
          - 80:80

      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./data:/api/data
          - ./configs:/api/configs
          - ./requirements/api:/api/requirements.txt
          - ./src/api.py:/api/src/api.py
          - ./src/db.py:/api/src/db.py
          - ./src/date.py:/api/src/date.py

      entrypoint:
          - /bin/sh
          - -c
          - |
           python3 -m pip install -r /api/requirements.txt && python3 /api/src/api.py

      links:
          - database

  api_refresher:
      image: python
      container_name: api_refresher
      
      logging:
            driver: "json-file"
            options:
                  max-size: "1m"
                  max-file: "5"

      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./data:/api/data
          - ./configs:/api/configs
          - ./requirements/refresher:/api/requirements.txt
          - ./src/refresher.py:/api/src/refresher.py
          - ./src/db.py:/api/src/db.py

      entrypoint:
          - /bin/sh
          - -c
          - |
           python3 -m pip install -r /api/requirements.txt && python3 /api/src/refresher.py

      links:
          - database

  database:
      image: mongo
      container_name: api_db

      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./db:/data/db

      logging:
            driver: "json-file"
            options:
                  max-size: "1m"
                  max-file: "5"

      healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo database:27017 --quiet
            interval: 60s
            timeout: 10s
            retries: 5
            start_period: 60s

      #environment:
      #    - MONGO_INITDB_ROOT_USERNAME=root
      #    - MONGO_INITDB_ROOT_PASSWORD=password_will_be_here