version: "2.3"

services:
  api:
      image: alpine
      container_name: api

      restart: on-failure
      
      logging:
            driver: "json-file"
            options:
                  max-size: "1m"
                  max-file: "5"

      healthcheck:
            test: curl -Ss http://api:8080/test || echo 1
            interval: 60s
            timeout: 10s
            retries: 5
            start_period: 60s

      ports:
          - 8080:8080

      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./src/api/bin/api:/api

      entrypoint:
          - /bin/sh
          - -c
          - |
           apk add --no-cache libc6-compat && \
           ./api --db-address $DB_ADDRESS --db-port $DB_PORT --port $API_PORT --passwd $PASSWD --compress

      links:
          - database

  api_refresher:
      image: api_refresher_img
      container_name: api_refresher

      restart: on-failure
      
      logging:
            driver: "json-file"
            options:
                  max-size: "1m"
                  max-file: "5"

      volumes:
          - /etc/localtime:/etc/localtime:ro

      links:
          - database

  database:
      image: mongo
      container_name: api_db

      restart: on-failure

      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./db_data:/data/db

      logging:
            driver: "json-file"
            options:
                  max-size: "1m"
                  max-file: "5"

      healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo database:27017 --quiet
            interval: 60s
            timeout: 10s
            retries: 5
            start_period: 60s